services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - database
    env_file:
      .env

  database:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "robots"
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - postgresql:/var/lib/postgresql/data

volumes:
  postgresql:
