version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgresql://nick:nick@database:5432/robots
    networks:
      - backend

  database:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "robots"
      POSTGRES_USER: "nick"
      POSTGRES_PASSWORD: "nick"
    volumes:
      - postgresql:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  postgresql:

networks:
  backend:
    driver: bridge
